# build stage
FROM node:20-bullseye AS build
WORKDIR /app

# copiem doar package.json și package-lock.json pentru cache eficient
COPY package*.json ./

# instalăm dependențele
RUN npm install

# copiem restul codului
COPY . .

# build production
RUN npm run build

# production stage
FROM nginx:alpine
# copiem build-ul în nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
