# build stage
FROM node:20-alpine AS build
WORKDIR /app

# copiem doar package.json și package-lock.json pentru cache eficient
COPY package*.json ./

RUN npm install

# copiem restul codului
COPY . .

RUN npm run build

# production stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
